---
params:
  save_params_as: "params.Rds"

  # Introduction
  title: TRUE

  # People and place
  title_people_and_place: TRUE
  population: TRUE
  deprivation: TRUE

  # Best start in life
  title_best_start_in_life: TRUE
  child_admissions: TRUE
  injury_admiss_under_5: TRUE
  injury_admiss_under_15: TRUE
  injury_admiss_15_to_24: TRUE
  reception_obesity: TRUE
  reception_overweight: TRUE
  year_6_obesity: TRUE
  year_6_overweight: TRUE
  
  # Living well
  title_living_well: TRUE
  life_expectancy_females: TRUE
  life_expectancy_males: TRUE
  unemployment: TRUE
  long_term_unemployment: TRUE
  qof_learning_disability: TRUE
  qof_hypertension: TRUE
  qof_epilepsy: TRUE
  qof_diabetes: TRUE
  qof_copd: TRUE
  qof_hf: TRUE
  qof_chd: TRUE
  emergency_admiss_all: TRUE
  emergency_admiss_chd: TRUE
  emergency_admiss_stroke: TRUE
  emergency_admiss_heart_attack: TRUE
  emergency_admiss_copd: TRUE
  emergency_admiss_self_harm: TRUE
  
  # Healthy ageing
  title_health_ageing: TRUE
  qof_stroke: TRUE
  qof_dementia: TRUE
  qof_ckd: TRUE
  emergency_admiss_hip_fracture: TRUE
  deaths_all_causes: TRUE
  deaths_under_75: TRUE
  deaths_preventable: TRUE
  deaths_cancer: TRUE
  deaths_cancer_under_75: TRUE
  deaths_circulatory_disease: TRUE
  deaths_circulatory_disease_under_75: TRUE
  deaths_chd: TRUE
  deaths_stroke: TRUE
  deaths_respiratory: TRUE
  
  # Healthy places
  title_healthy_place: TRUE
  fuel_poverty: TRUE
  access_gardenspace: TRUE
  access_public_greenspace: TRUE
  access_secondary_school: TRUE
---

```{r settings}

# set working directory
setwd(paste0("C:/Users/", Sys.getenv("username"), "/OneDrive - Royal Borough of Windsor and Maidenhead/projects_git/JHWBS-profiles/R"))

# Save dataset
save_dataset <- TRUE

# Do you want to load the lookup and data files
load_files <- TRUE

ward_name <- NULL
ward_code <- NULL

# Version number
version_num <- 0.43

# Load required packages
library(officer)
library(phiTools)
library(sf)
library(plyr)
library(openxlsx)

# Warning options
options(warn = 1) ## Show warnings as they occur, useful for finding and dealing with them.
options(scipen = 999) # Turn scientific notion off

# System time
t1 <- Sys.time()

# ---- PowerPoint template ----

# Open connection to pptx file
mydoc <- read_pptx(path = paste0("C:/Users/", Sys.getenv("username"), "/OneDrive - Royal Borough of Windsor and Maidenhead/PHI - Data and Analytics/References/Templates/RBWM-PHI-profiles-template.pptx"))

# slide number
slide_num <- 0

## Save the parameters in case we want to use them in a script
save_params_as <- params$save_params_as
saveRDS(params, file = save_params_as)

report_params <- params

## Choose which slides to include

# Introduction
incl_title <- report_params$title

# People and place
incl_title_people_and_place<- report_params$title_people_and_place
incl_population <- report_params$population
incl_deprivation <- report_params$deprivation

# Best start in life
incl_title_best_start_in_life <- report_params$title_best_start_in_life
incl_child_admissions <- report_params$child_admissions
incl_injury_admiss_under_5 <- report_params$injury_admiss_under_5
incl_injury_admiss_under_15 <- report_params$injury_admiss_under_15
incl_injury_admiss_15_to_24 <- report_params$injury_admiss_15_to_24
incl_reception_obesity <- report_params$reception_obesity
incl_reception_overweight <- report_params$reception_overweight
incl_year_6_obesity <- report_params$year_6_obesity
incl_year_6_overweight <- report_params$year_6_overweight

# Living well
incl_title_living_well <- report_params$title_living_well
incl_life_expectancy_females <- report_params$life_expectancy_females
incl_life_expectancy_males <- report_params$life_expectancy_males
incl_unemployment <- report_params$unemployment
incl_long_term_unemployment <- report_params$long_term_unemployment
incl_qof_learning_disability <- report_params$qof_learning_disability
incl_qof_hypertension <- report_params$qof_hypertension
incl_qof_epilepsy <- report_params$qof_epilepsy
incl_qof_diabetes <- report_params$qof_diabetes
incl_qof_copd <- report_params$qof_copd
incl_qof_hf <- report_params$qof_hf
incl_qof_chd <- report_params$qof_chd
incl_emergency_admiss_all <- report_params$emergency_admiss_all
incl_emergency_admiss_chd <- report_params$emergency_admiss_chd
incl_emergency_admiss_stroke <- report_params$emergency_admiss_stroke
incl_emergency_admiss_heart_attack <- report_params$emergency_admiss_heart_attack
incl_emergency_admiss_copd <- report_params$emergency_admiss_copd
incl_emergency_admiss_self_harm <- report_params$emergency_admiss_self_harm

# Healthy ageing
incl_title_health_ageing <- report_params$title_health_ageing
incl_qof_stroke <- report_params$qof_stroke
incl_qof_dementia <- report_params$qof_dementia
incl_qof_ckd <- report_params$qof_ckd
incl_emergency_admiss_hip_fracture <- report_params$emergency_admiss_hip_fracture
incl_deaths_all_causes <- report_params$deaths_all_causes
incl_deaths_under_75 <- report_params$deaths_under_75
incl_deaths_preventable <- report_params$deaths_preventable
incl_deaths_cancer <- report_params$deaths_cancer
incl_deaths_cancer_under_75 <- report_params$deaths_cancer_under_75
incl_deaths_circulatory_disease <- report_params$deaths_circulatory_disease
incl_deaths_circulatory_disease_under_75 <- report_params$deaths_circulatory_disease_under_75
incl_deaths_chd <- report_params$deaths_chd
incl_deaths_stroke <- report_params$deaths_stroke
incl_deaths_respiratory <- report_params$deaths_respiratory

# Healthy place
incl_title_healthy_place <- report_params$title_healthy_place
incl_fuel_poverty <- report_params$fuel_poverty
incl_access_gardenspace <- report_params$access_gardenspace
incl_access_public_greenspace <- report_params$access_public_greenspace
incl_access_secondary_school <- report_params$access_secondary_school


# Create empty data frame for summary table
summary <- data.frame(indicator = character(), 
                      comparison = character(), 
                      slide = numeric(), stringsAsFactors = FALSE) 

# Create empty data frame for dataset
dataset <- data.frame()

#---- Data ----
rbwm_code <- "E06000040"
eng_code <- "E92000001"

# england and wales LSOA to ward to lad
lsoa_ward_lad <- read.csv(paste0("C:/Users/", Sys.getenv("username"), "/OneDrive - Royal Borough of Windsor and Maidenhead/PHI - Data and Analytics/References/Geography/ONS Open Geography Portal/Lookups/LSOA to Ward to LAD/LSOA_(2021)_to_Electoral_Ward_(2024)_to_LAD_(2024)_Best_Fit_Lookup_in_EW.csv"))

# RBWM postcodes
rbwm_pcodes <- readRDS(paste0("C:/Users/", Sys.getenv("username"), "/OneDrive - Royal Borough of Windsor and Maidenhead/PHI - Data and Analytics/References/Geography/ONS Open Geography Portal/NSPL/processed-data/nspl-rbwm-postcodes.Rds"))

# RBWM lsoas
i <- lsoa_ward_lad$LAD24CD == rbwm_code
rbwm_lsoas <- lsoa_ward_lad$LSOA21CD[i]

# rbwm wards
i <- lsoa_ward_lad$LAD24CD == rbwm_code
rbwm_wards <- unique(lsoa_ward_lad$WD24CD[i])

# England and Wales MSOA to ward to LAD
msoa_ward_lad <- read.csv(paste0("C:/Users/", Sys.getenv("username"), "/OneDrive - Royal Borough of Windsor and Maidenhead/PHI - Data and Analytics/References/Geography/ONS Open Geography Portal/Lookups/MSOA to Ward to LAD/MSOA_(2021)_to_Ward_(2024)_to_LAD_(2024)_Best_Fit_Lookup_in_EW.csv"))

# RBWM MSOAs
i <- msoa_ward_lad$LAD24CD == rbwm_code
rbwm_msoas <- msoa_ward_lad$MSOA21CD[i]

# ONS LA pop estimates
pop_la <- readRDS(paste0("C:/Users/", Sys.getenv("username"), "/OneDrive - Royal Borough of Windsor and Maidenhead/PHI - Data and Analytics/Datasets/ONS/nomis/Population/Population estimates/Local authority/processed data/ons-la-pop.Rds"))

# ONS lsoa pop estimates
pop_lsoa <- readRDS(paste0("C:/Users/", Sys.getenv("username"), "/OneDrive - Royal Borough of Windsor and Maidenhead/PHI - Data and Analytics/Datasets/ONS/nomis/Population/Population estimates/lsoa/processed data/ons-lsoa-pop.Rds"))

# LSOA deprivation
dep <- data_deprivation_pop(population = pop_lsoa)

# RBWM GPs
epraccur <- readRDS(paste0("C:/Users/", Sys.getenv("username"), "/OneDrive - Royal Borough of Windsor and Maidenhead/PHI - Data and Analytics/Datasets/NHS Digital/GP and GP practice related data/processed-data/epraccur.Rds"))

rbwm_gp <- merge(x = epraccur, y = rbwm_pcodes, by = "pcdNoSpaces")
rbwm_gp <- rbwm_gp[, c("Organisation Code", "oseast1m", "osnrth1m")]

#### Fingertips data ####
fingertips_msoa <- data_fingertips_msoa()
fingertips_gp <- data_fingertips_gp()

# remove non_rbwm gps but keep england
fingertips_gp <- fingertips_gp[fingertips_gp$AreaCode %in% 
                                 c(rbwm_gp$`Organisation Code`, rbwm_code, 
                                   eng_code), ]

fingertips_gp <- merge(x = fingertips_gp, y = rbwm_gp, by.x = "AreaCode",
                       by.y = "Organisation Code", all.x = TRUE)

#---- Shape files ----
#### LSOAs ####
shp_lsoa <- data_shape_lsoa()

# RBWM LSOAs
i <- shp_lsoa$AreaCode %in% rbwm_lsoas
shp_lsoa_rbwm <- shp_lsoa[i, ]

#### MSOAs ####
shp_msoa <- data_shape_msoa()

```

```{r title, eval = incl_title}

slide_num <- slide_num + 1

# Add slide
mydoc <- add_slide(mydoc, layout = "title logo", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = paste0("The Royal Borough of Windsor \u0026 Maidenhead Health and Wellbeing profile"))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "subtitle"),
                 value = paste0("Public Health ", format(Sys.Date(), "%d/%m/%Y")))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
  
```

```{r title_people_and_place, eval = incl_title_people_and_place}

# ---- People and place ----
slide_num <- slide_num + 1
theme <- NULL
title <- paste0("People and place")
short_title <- NULL


# Add slide
mydoc <- add_slide(mydoc, layout = "title", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
  
```

```{r population, eval = incl_population}

slide_num <- slide_num + 1
theme <- NULL
title <- paste0("Population")
short_title <- NULL

# Outputs
pop_pyramid <- plot_pop_pyramid(data = pop_la)
pop_comp <- plot_pop_area_comp_eng(data = pop_la)

# Add slide
mydoc <- add_slide(mydoc, layout = "two content", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "content left"), 
                 value = pop_pyramid$plot, alt_text = pop_pyramid$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "content right"), 
                 value = pop_comp$plot, alt_text = pop_comp$alt_text)

```

```{r deprivation, eval = incl_deprivation}

slide_num <- slide_num + 1
theme <- NULL
title <- paste0("Deprivation")
short_title <- NULL

# Outputs
pop_dep_bar_plot <- plot_dep_pop(data = dep)
dep_map <- map_deprivation(deprivation_data = dep, lsoa_shape = shp_lsoa,
                           lsoas_to_plot = rbwm_lsoas)

# Add slide
mydoc <- add_slide(mydoc, layout = "two content", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "content left"), 
                 value = pop_dep_bar_plot$plot, alt_text = pop_dep_bar_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "content right"), 
                 value = dep_map$ggplot, alt_text = dep_map$alt_text)

```

```{r title_best_start_in_life, eval = incl_title_best_start_in_life}

# ---- Best start in life ----
slide_num <- slide_num + 1
theme <- NULL
title <- paste0("Best start in life")
short_title <- NULL


# Add slide
mydoc <- add_slide(mydoc, layout = "title", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
  
```

```{r child_admissions, eval = incl_child_admissions}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93115
ind_sex <- "Persons"
ind_age <- "Under 5 yrs"
title <- paste0("Emergency hospital admissions in under 5 years old, ", tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Emergency hospital admissions (", ind_age, ")")
additional_text <- NULL
notes <- NULL

value_type <- "Crude rate per 1,000"
value_type_short <- "per 1,000"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r injury_admiss_under_5, eval = incl_injury_admiss_under_5}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93114
ind_sex <- "Persons"
ind_age <- "Under 5 yrs"
title <- paste0("Emergency hospital admissions for injuries, ",
                tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Emergency admissions for injuries (", ind_age, ")")
additional_text <- NULL
notes <- NULL

value_type <- "Crude rate per 1,000"
value_type_short <- "per 1,000"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r injury_admiss_under_15, eval = incl_injury_admiss_under_15}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93219
ind_sex <- "Persons"
ind_age <- "Under 15 yrs"
title <- paste0("Emergency hospital admissions for injuries, ", 
                tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Emergency admissions for injuries (", ind_age, ")")
additional_text <- NULL
notes <- NULL

value_type <- "Crude rate per 1,000"
value_type_short <- "per 1,000"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r injury_admiss_15_to_24, eval = incl_injury_admiss_15_to_24}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93224
ind_sex <- "Persons"
ind_age <- "15 to 24 yrs"
title <- paste0("Emergency hospital admissions for injuries, ", 
                tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Emergency admissions for injuries (", ind_age, ")")
additional_text <- NULL
notes <- NULL

value_type <- "Crude rate per 1,000"
value_type_short <- "per 1,000"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r reception_obesity, eval = incl_reception_obesity}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93105
ind_sex <- "Persons"
ind_age <- "4-5 yrs"
title <- paste0("Reception: Prevalence of obesity, ", tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Reception: Prevalence of obesity (", ind_age, ")")
additional_text <- "Obesity: including severe obesity.\n\n"
notes <- "\nNotes: Due to the impact of COVID-19 on the NCMP data collection, data was not published for the 2018/19-20/21 time period."

value_type <- "Proportion (%)"
value_type_short <- "%"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score CI method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = "Proportion (%)")
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r reception_overweight, eval = incl_reception_overweight}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93106
ind_sex <- "Persons"
ind_age <- "4-5 yrs"
title <- paste0("Reception: Prevalence of overweight, ", tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Reception: Prevalence of overweight (", ind_age, ")")
additional_text <- "Overweight: including obesity\n\n"
notes <- "\nNotes: Due to the impact of COVID-19 on the NCMP data collection, data was not published for the 2018/19-20/21 time period."

value_type <- "Proportion (%)"
value_type_short <- "%"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score CI method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = "Proportion (%)")
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r year_6_obesity, eval = incl_year_6_obesity}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93107
ind_sex <- "Persons"
ind_age <- "10-11 yrs"
title <- paste0("Year 6: Prevalence of obesity, ", tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Year 6: Prevalence of obesity (", ind_age, ")")
additional_text <- "Obesity: including severe obesity.\n\n"
notes <- "\nNotes: Due to the impact of COVID-19 on the NCMP data collection, data was not published for the 2018/19-20/21 time period."

value_type <- "Proportion (%)"
value_type_short <- "%"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score CI method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = "Proportion (%)")
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r year_6_overweight, eval = incl_year_6_overweight}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93108
ind_sex <- "Persons"
ind_age <- "10-11 yrs"
title <- paste0("Year 6: Prevalence of overweight, ", tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Year 6: Prevalence of overweight (", ind_age, ")")
additional_text <- "Overweight: including obesity.\n\n"
notes <- "\nNotes: Due to the impact of COVID-19 on the NCMP data collection, data was not published for the 2018/19-20/21 time period."

value_type <- "Proportion (%)"
value_type_short <- "%"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score CI method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = "Proportion (%)")
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r title_living_well, eval = incl_title_living_well}

# ---- Living well ----
slide_num <- slide_num + 1
theme <- NULL
title <- paste0("Living well")
short_title <- NULL


# Add slide
mydoc <- add_slide(mydoc, layout = "title", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
  
```

```{r life_expectancy_females, eval = incl_life_expectancy_females}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93283
ind_sex <- "Female"
ind_age <- NULL
title <- paste0("Life expectancy at birth, upper age band 90 and over (",
                tolower(ind_sex), ")")
short_title <- paste0("Life expectancy at birth (", ind_sex, ")")
additional_text <- NULL
notes <- NULL

value_type <- "Life expectancy (years)"
value_type_short <- "Years"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Chiang CL (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID & 
                       fingertips_msoa$Sex == ind_sex, ]
x <- create_comp_rag(data = x, low_is_good = FALSE)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = timeperiod)
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r life_expectancy_males, eval = incl_life_expectancy_males}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93283
ind_sex <- "Male"
ind_age <- NULL
title <- paste0("Life expectancy at birth, upper age band 90 and over (",
                tolower(ind_sex), ")")
short_title <- paste0("Life expectancy at birth (", ind_sex, ")")
additional_text <- NULL
notes <- NULL

value_type <- "Life expetancy (years)"
value_type_short <- "Years"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Chiang CL (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID & 
                       fingertips_msoa$Sex == ind_sex, ]
x <- create_comp_rag(data = x, low_is_good = FALSE)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = timeperiod)
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r unemployment, eval = incl_unemployment}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93097
ind_sex <- "Persons"
ind_age <- "16-64 yrs"
title <- paste0("Unemployment (Percentage of the working age population claiming out of work benefit) (", tolower(ind_sex), "), (", tolower(ind_age), ")")
short_title <- paste0("Unemployment (", ind_age, ")")
additional_text <- NULL
notes <- NULL

value_type <- "Proportion (%)"
value_type_short <- "%"
timeperiod <- "financial years"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score CI method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = timeperiod)
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r long_term_unemployment, eval = incl_long_term_unemployment}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93098
ind_sex <- "Persons"
ind_age <- "16-64 yrs"
title <- paste0("Long-Term Unemployment (", tolower(ind_sex), "), (", tolower(ind_age), ")")
short_title <- paste0("Long-Term Unemployment (", ind_age, ")")
additional_text <- NULL
notes <- NULL

value_type <- "Crude rate per 1,000"
value_type_short <- "per 1,000"
timeperiod <- "financial years"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = timeperiod)
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r qof_learning_disability, eval = incl_qof_learning_disability}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 200
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Learning disability: QOF prevalence (", tolower(ind_sex), "), (", tolower(ind_age), ")")
short_title <- paste0("Learning disability")
additional_text <- NULL
notes <- NULL

value_type <- "Proportion (%)"
value_type_short <- "%"
timeperiod <- "financial years"
original_geography <- "GP"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_gp[fingertips_gp$IndicatorID == ind_ID, ]
x <- create_comp_bob(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = timeperiod)
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_comp_locations(data = x, shape_file = shp_lsoa_rbwm, 
                          locations_to_map = rbwm_gp$`Organisation Code`)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# drop eastings and northings for bind
x$oseast1m <- NULL
x$osnrth1m <- NULL

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r qof_hypertension, eval = incl_qof_hypertension}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 219
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Hypertension: QOF prevalence (", tolower(ind_sex), "), (", tolower(ind_age), ")")
short_title <- paste0("Hypertension: QOF prevalence")
additional_text <- NULL
notes <- NULL

value_type <- "Proportion (%)"
value_type_short <- "%"
timeperiod <- "financial years"
original_geography <- "GP"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_gp[fingertips_gp$IndicatorID == ind_ID, ]
x <- create_comp_bob(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = timeperiod)
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_comp_locations(data = x, shape_file = shp_lsoa_rbwm, 
                          locations_to_map = rbwm_gp$`Organisation Code`)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# drop eastings and northings for bind
x$oseast1m <- NULL
x$osnrth1m <- NULL

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r qof_epilepsy, eval = incl_qof_epilepsy}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 224
ind_sex <- "Persons"
ind_age <- "18+ yrs"
title <- paste0("Epilepsy: QOF prevalence (", tolower(ind_sex), "), (", tolower(ind_age), ")")
short_title <- paste0("Epilepsy: QOF prevalence")
additional_text <- NULL
notes <- NULL

value_type <- "Proportion (%)"
value_type_short <- "%"
timeperiod <- "financial years"
original_geography <- "GP"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_gp[fingertips_gp$IndicatorID == ind_ID, ]
x <- create_comp_bob(data = x)

#latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
# trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
#                                    show_comp_legend = FALSE, 
#                                    timeperiod_format = timeperiod)
area_comp <- plot_area_comparison(data = x, area_code = NULL,
                                  value_type = value_type, show_legend = FALSE)
map <- map_comp_locations(data = x, shape_file = shp_lsoa_rbwm, 
                          locations_to_map = rbwm_gp$`Organisation Code`)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# drop eastings and northings for bind
x$oseast1m <- NULL
x$osnrth1m <- NULL

# add indicator to master dataset
dataset <- rbind(dataset, x)

unavailable_note <- paste0("Data unavailable for counties & UAs")

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = unavailable_note)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = unavailable_note)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r qof_diabetes, eval = incl_qof_diabetes}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 241
ind_sex <- "Persons"
ind_age <- "17+ yrs"
title <- paste0("Diabetes: QOF prevalence (", tolower(ind_sex), "), (", tolower(ind_age), ")")
short_title <- paste0("Diabetes: QOF prevalence")
additional_text <- NULL
notes <- NULL

value_type <- "Proportion (%)"
value_type_short <- "%"
timeperiod <- "financial years"
original_geography <- "GP"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_gp[fingertips_gp$IndicatorID == ind_ID, ]
x <- create_comp_bob(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = timeperiod)
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_comp_locations(data = x, shape_file = shp_lsoa_rbwm, 
                          locations_to_map = rbwm_gp$`Organisation Code`)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# drop eastings and northings for bind
x$oseast1m <- NULL
x$osnrth1m <- NULL

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata)

```

```{r qof_copd, eval = incl_qof_copd}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 253
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Chronic Obstructive Pulmonary Disease: QOF prevalence (", tolower(ind_sex), "), (", tolower(ind_age), ")")
short_title <- paste0("COPD: QOF prevalence")
additional_text <- NULL
notes <- NULL

value_type <- "Proportion (%)"
value_type_short <- "%"
timeperiod <- "financial years"
original_geography <- "GP"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_gp[fingertips_gp$IndicatorID == ind_ID, ]
x <- create_comp_bob(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = timeperiod)
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_comp_locations(data = x, shape_file = shp_lsoa_rbwm, 
                          locations_to_map = rbwm_gp$`Organisation Code`)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# drop eastings and northings for bind
x$oseast1m <- NULL
x$osnrth1m <- NULL

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata)

```

```{r qof_hf, eval = incl_qof_hf}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 262
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Heart Failure: QOF prevalence (", tolower(ind_sex), "), (", tolower(ind_age), ")")
short_title <- paste0("Heart Failure: QOF prevalence")
additional_text <- NULL
notes <- NULL

value_type <- "Proportion (%)"
value_type_short <- "%"
timeperiod <- "financial years"
original_geography <- "GP"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_gp[fingertips_gp$IndicatorID == ind_ID, ]
x <- create_comp_bob(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = timeperiod)
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_comp_locations(data = x, shape_file = shp_lsoa_rbwm, 
                          locations_to_map = rbwm_gp$`Organisation Code`)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# drop eastings and northings for bind
x$oseast1m <- NULL
x$osnrth1m <- NULL

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata)

```

```{r qof_chd, eval = incl_qof_chd}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 273
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Coronary heart disease: QOF prevalence (", tolower(ind_sex), "), (", tolower(ind_age), ")")
short_title <- paste0("CHD: QOF prevalence")
additional_text <- NULL
notes <- NULL

value_type <- "Proportion (%)"
value_type_short <- "%"
timeperiod <- "financial years"
original_geography <- "GP"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_gp[fingertips_gp$IndicatorID == ind_ID, ]
x <- create_comp_bob(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = timeperiod)
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_comp_locations(data = x, shape_file = shp_lsoa_rbwm, 
                          locations_to_map = rbwm_gp$`Organisation Code`)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# drop eastings and northings for bind
x$oseast1m <- NULL
x$osnrth1m <- NULL

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata)

```

```{r emergency_admiss_all, eval = incl_emergency_admiss_all}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93227
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Emergency hospital admissions for all causes, ",
                tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Emergency admissions for all causes")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r emergency_admiss_chd, eval = incl_emergency_admiss_chd}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93229
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("EEmergency hospital admissions for coronary heart disease, ",
                tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Emergency admissions for CHD")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r emergency_admiss_stroke, eval = incl_emergency_admiss_stroke}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93231
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Emergency hospital admissions for stroke, ",
                tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Emergency admissions for stroke")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r emergency_admiss_heart_attack, eval = incl_emergency_admiss_heart_attack}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93232
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Emergency hospital admissions for myocardial infarction (heart attack), ",
                tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Emergency admissions for heart attack")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r emergency_admiss_copd, eval = incl_emergency_admiss_copd}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93233
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Emergency hospital admissions for chronic obstructive pulmonary disease (COPD), ",
                tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Emergency admissions for COPD")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r emergency_admiss_self_harm, eval = incl_emergency_admiss_self_harm}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93239
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Emergency hospital admissions for intentional self harm, ",
                tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Emergency admissions for self harm")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r title_health_ageing, eval = incl_title_health_ageing}

# ---- Healthy ageing ----
slide_num <- slide_num + 1
theme <- NULL
title <- paste0("Healthy ageing")
short_title <- NULL


# Add slide
mydoc <- add_slide(mydoc, layout = "title", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
  
```

```{r qof_stroke, eval = incl_qof_stroke}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 212
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Stroke: QOF prevalence (", tolower(ind_sex), "), (", tolower(ind_age), ")")
short_title <- paste0("Stroke: QOF prevalence")
additional_text <- NULL
notes <- NULL

value_type <- "Proportion (%)"
value_type_short <- "%"
timeperiod <- "financial years"
original_geography <- "GP"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_gp[fingertips_gp$IndicatorID == ind_ID, ]
x <- create_comp_bob(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = timeperiod)
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_comp_locations(data = x, shape_file = shp_lsoa_rbwm, 
                          locations_to_map = rbwm_gp$`Organisation Code`)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# drop eastings and northings for bind
x$oseast1m <- NULL
x$osnrth1m <- NULL

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r qof_dementia, eval = incl_qof_dementia}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 247
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Dementia: QOF prevalence (", tolower(ind_sex), "), (", tolower(ind_age), ")")
short_title <- paste0("Dementia: QOF prevalence")
additional_text <- NULL
notes <- NULL

value_type <- "Proportion (%)"
value_type_short <- "%"
timeperiod <- "financial years"
original_geography <- "GP"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_gp[fingertips_gp$IndicatorID == ind_ID, ]
x <- create_comp_bob(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = timeperiod)
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_comp_locations(data = x, shape_file = shp_lsoa_rbwm, 
                          locations_to_map = rbwm_gp$`Organisation Code`)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# drop eastings and northings for bind
x$oseast1m <- NULL
x$osnrth1m <- NULL

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r qof_ckd, eval = incl_qof_ckd}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 258
ind_sex <- "Persons"
ind_age <- "18+ yrs"
title <- paste0("Chronic Kidney Disease: QOF prevalence (", tolower(ind_sex), "), (", tolower(ind_age), ")")
short_title <- paste0("CKD: QOF prevalence")
additional_text <- NULL
notes <- NULL

value_type <- "Proportion (%)"
value_type_short <- "%"
timeperiod <- "financial years"
original_geography <- "GP"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_gp[fingertips_gp$IndicatorID == ind_ID, ]
x <- create_comp_bob(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = timeperiod)
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_comp_locations(data = x, shape_file = shp_lsoa_rbwm, 
                          locations_to_map = rbwm_gp$`Organisation Code`)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# drop eastings and northings for bind
x$oseast1m <- NULL
x$osnrth1m <- NULL

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r emergency_admiss_hip_fracture, eval = incl_emergency_admiss_hip_fracture}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93241
ind_sex <- "Persons"
ind_age <- "65 yrs+"
title <- paste0("Emergency hospital admissions for hip fracture, ",
                tolower(ind_sex), ", ", tolower(ind_age))
short_title <- paste0("Emergency admissions for hip fracture (", ind_age, ")")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r deaths_all_causes, eval = incl_deaths_all_causes}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93250
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Deaths from all causes, ", tolower(ind_sex), ", ",
                tolower(ind_age))
short_title <- paste0("Deaths from all causes")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r deaths_under_75, eval = incl_deaths_under_75}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93252
ind_sex <- "Persons"
ind_age <- "Under 75 yrs"
title <- paste0("Deaths from all causes, ", tolower(ind_sex), ", ",
                tolower(ind_age))
short_title <- paste0("Deaths from all causes (", ind_age, ")")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r deaths_preventable, eval = incl_deaths_preventable}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93480
ind_sex <- "Persons"
ind_age <- "Under 75 yrs"
title <- paste0("Deaths from causes considered preventable, ", tolower(ind_sex), ", ",
                tolower(ind_age))
short_title <- paste0("Deaths from preventable causes (", ind_age, ")")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r deaths_cancer, eval = incl_deaths_cancer}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93253
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Deaths from all cancer, ", tolower(ind_sex), ", ",
                tolower(ind_age))
short_title <- paste0("Deaths from all cancer")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r deaths_cancer_under_75, eval = incl_deaths_cancer_under_75}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93254
ind_sex <- "Persons"
ind_age <- "Under 75 yrs"
title <- paste0("Deaths from all cancer, ", tolower(ind_sex), ", ",
                tolower(ind_age))
short_title <- paste0("Deaths from all cancer (", ind_age, ")")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r deaths_circulatory_disease, eval = incl_deaths_circulatory_disease}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93255
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Deaths from circulatory disease, ", tolower(ind_sex), ", ",
                tolower(ind_age))
short_title <- paste0("Deaths from circulatory disease")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r deaths_circulatory_disease_under_75, eval = incl_deaths_circulatory_disease_under_75}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93256
ind_sex <- "Persons"
ind_age <- "Under 75 yrs"
title <- paste0("Deaths from circulatory disease, ", tolower(ind_sex), ", ",
                tolower(ind_age))
short_title <- paste0("Deaths from circulatory disease (", ind_age, ")")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r deaths_chd, eval = incl_deaths_chd}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93257
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Deaths from coronary heart disease, ", tolower(ind_sex), ", ",
                tolower(ind_age))
short_title <- paste0("Deaths from CHD")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r deaths_stroke, eval = incl_deaths_stroke}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93259
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Deaths from stroke, ", tolower(ind_sex), ", ",
                tolower(ind_age))
short_title <- paste0("Deaths from stroke")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r deaths_respiratory, eval = incl_deaths_respiratory}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
ind_ID <- 93260
ind_sex <- "Persons"
ind_age <- "All ages"
title <- paste0("Deaths from respiratory diseases, ", tolower(ind_sex), ", ",
                tolower(ind_age))
short_title <- paste0("Deaths from respiratory diseases")
additional_text <- NULL
notes <- NULL

value_type <- "Indirectly standardised ratio"
value_type_short <- "per 100"
timeperiod <- "periods"
original_geography <- "MSOA"
CI_level <- 0.95
confidence_interval_method <- paste0("Byar's method method (", CI_level * 100,"%)")
source <- paste0("Office for Health Improvement and Disparities. Fingertips. Indicator ID: ", ind_ID)

x <- fingertips_msoa[fingertips_msoa$IndicatorID == ind_ID, ]
x <- create_comp_rag(data = x)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))
trend_plot <- plot_indicator_trend(data = x, value_type = value_type, 
                                   show_comp_legend = FALSE, 
                                   timeperiod_format = "periods")
area_comp <- plot_area_comparison(data = x, value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_msoa, 
                         areas_to_map = rbwm_msoas)

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)

# add indicator to master dataset
dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = short_title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot$plot, alt_text = trend_plot$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r title_healthy_place, eval = incl_title_healthy_place}

# ---- Healthy place ----
slide_num <- slide_num + 1
theme <- NULL
title <- paste0("Healthy place")
short_title <- NULL


# Add slide
mydoc <- add_slide(mydoc, layout = "title", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
  
```

```{r fuel_poverty, eval = incl_fuel_poverty}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
# ind_ID <- 
# ind_sex <- 
# ind_age <- 
title <- paste0("Fuel poverty measured as low income low energy efficiency (LILEE)")
short_title <- paste0("Fuel poverty")
additional_text <- NULL
notes <- NULL
#caveats <- NULL

value_type <- "Proportion (%)"
value_type_short <- "%"
# timeperiod <- "periods"
original_geography <- "MSOA"
#CI_level <- 0.95
confidence_interval_method <- paste0("Sample quantiles")
source <- paste0("Department for Energy Security and Net Zero. Sub-regional fuel poverty data")

x <- read.xlsx(paste0("C:/Users/", Sys.getenv("username"), "/OneDrive - Royal Borough of Windsor and Maidenhead/PHI - Data and Analytics/Datasets/gov.uk/Sub-regional fuel poverty data/source-data/Sub-regional_fuel_poverty_statistics_2023.xlsx"), 
               sheet = "Table 4", startRow = 3)

x <- merge(x = x, y = lsoa_ward_lad, by.x = "LSOA.Code", by.y = "LSOA21CD")

ward <- aggregate(cbind(Number.of.households.in.fuel.poverty, 
                        Number.of.households) ~ 
                    WD24CD + WD24NM,
                  data = x, FUN = sum)
colnames(ward) <- c("AreaCode", "AreaName", "Count", "Denominator")
ward$AreaType <- "Ward"


LA <- aggregate(cbind(Number.of.households.in.fuel.poverty, 
                      Number.of.households) ~ 
                  Local.Authority.Code + Local.Authority.Name,
                data = x, FUN = sum)
colnames(LA) <- c("AreaCode", "AreaName", "Count", "Denominator")
LA$AreaType <- "Local authority"

i <- x$Country.code == eng_code
eng <- slide_num <- slide_num + 1
theme <- NULL

# Metadata
# ind_ID <- 
# ind_sex <- 
# ind_age <- 
title <- paste0("Fuel poverty measured as low income low energy efficiency")
short_title <- paste0("Fuel poverty")
additional_text <- NULL
notes <- NULL
#caveats <- NULL

value_type <- "Proportion (%)"
value_type_short <- "%"
# timeperiod <- "periods"
original_geography <- "MSOA"
#CI_level <- 0.95
confidence_interval_method <- paste0("Sample quantiles")
source <- paste0("Department for Energy Security and Net Zero. Sub-regional fuel poverty data")

x <- read.xlsx(paste0("C:/Users/", Sys.getenv("username"), "/OneDrive - Royal Borough of Windsor and Maidenhead/PHI - Data and Analytics/Datasets/gov.uk/Sub-regional fuel poverty data/source-data/Sub-regional_fuel_poverty_statistics_2023.xlsx"), 
               sheet = "Table 4", startRow = 3)

x <- merge(x = x, y = lsoa_ward_lad, by.x = "LSOA.Code", by.y = "LSOA21CD")

ward <- aggregate(cbind(Number.of.households.in.fuel.poverty, 
                        Number.of.households) ~ 
                    WD24CD + WD24NM,
                  data = x, FUN = sum)
colnames(ward) <- c("AreaCode", "AreaName", "Count", "Denominator")
ward$AreaType <- "Ward"


LA <- aggregate(cbind(Number.of.households.in.fuel.poverty, 
                      Number.of.households) ~ 
                  Local.Authority.Code + Local.Authority.Name,
                data = x, FUN = sum)
colnames(LA) <- c("AreaCode", "AreaName", "Count", "Denominator")
LA$AreaType <- "Local authority"

eng <- data.frame(AreaCode = eng_code, AreaName = "England",
                  Count = sum(x$Number.of.households.in.fuel.poverty),
                  Denominator = sum(x$Number.of.households))
eng$AreaType <- "England"

x <- x[, c("LSOA.Code", "LSOA.Name", "Number.of.households.in.fuel.poverty",
           "Number.of.households")]
colnames(x) <- c("AreaCode", "AreaName", "Count", "Denominator")
x$AreaType <- "LSOA"

x <- rbind(x, ward, LA, eng)

x$Value <- x$Count / x$Denominator * 100
x$Timeperiod <- 2023

x$LowerCI95Limit <- PHEindicatormethods:::wilson_lower(x = x$Count, n = x$Denominator) * 100
x$LowerCI99.8Limit <- NA
x$UpperCI95Limit <- PHEindicatormethods:::wilson_upper(x = x$Count, n = x$Denominator) * 100
x$UpperCI99.8Limit <- NA

x <- create_comp_rag(data = x, low_is_good = FALSE)

data <- x
eng <- data[data$AreaCode == eng_code, ]
rbwm <- data[data$AreaCode == rbwm_code, ]

#### Local Authorities ####
x <- data[data$AreaType == "Local authority", ]

# Create quintiles for all LSOA data
quintiles <- quantile(x$Value, probs = seq(0, 1, by = 0.2), na.rm = TRUE) 
quintiles[1] <- round_any(quintiles[1], 0.1, f = floor)
quintiles[2:5] <- round_any(quintiles[2:5], 0.1, f = round)
quintiles[6] <- round_any(quintiles[6], 0.1, f = ceiling)

x <- rbind(x, eng)

x$Quintile <- with(x, cut(Value, breaks = quintiles, include.lowest = TRUE, 
                          labels = 1:5))
levels(x$Quintile) <- gsub(",", " - ", levels(x$Quintile))
# The notation (a - b] means ">a and <=b".

levels(x$Quintile) <- c(levels(x$Quintile), "Not compared")
x$Quintile[is.na(x$Value)] <- "Not compared"

x$Quintile[x$AreaCode == eng_code] <- "Not compared"

x$Colour <- NA
x$Colour[x$Quintile == 1] <- "#342346FF"
x$Colour[x$Quintile == 2] <- "#40498EFF"
x$Colour[x$Quintile == 3] <- "#357BA2FF"
x$Colour[x$Quintile == 4] <- "#38AAACFF"
x$Colour[x$Quintile == 5] <- "#78D6AEFF"
x$Colour[x$Quintile == "Not compared"] <- "grey"

x$Colour <- factor(x$Colour, c("#342346FF", "#40498EFF", "#357BA2FF", "#38AAACFF",
                               "#78D6AEFF", "grey"))

latest_value <- plot_latest_value_quint(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))

#### RBWM wards ###
i <- data$AreaCode %in% rbwm_wards
x <- data[i, ]

# Create quintiles for all LSOA data
quintiles <- quantile(x$Value, probs = seq(0, 1, by = 0.2), na.rm = TRUE) 
quintiles[1] <- round_any(quintiles[1], 0.1, f = floor)
quintiles[2:5] <- round_any(quintiles[2:5], 0.1, f = round)
quintiles[6] <- round_any(quintiles[6], 0.1, f = ceiling)

x <- rbind(x, rbwm, eng)

x$Quintile <- with(x, cut(Value, breaks = quintiles, include.lowest = TRUE, 
                          labels = 1:5))
levels(x$Quintile) <- gsub(",", " - ", levels(x$Quintile))
# The notation (a - b] means ">a and <=b".

levels(x$Quintile) <- c(levels(x$Quintile), "Not compared")
x$Quintile[is.na(x$Value)] <- "Not compared"

x$Quintile[x$AreaCode == eng_code] <- "Not compared"

x$Colour <- NA
x$Colour[x$Quintile == 1] <- "#342346FF"
x$Colour[x$Quintile == 2] <- "#40498EFF"
x$Colour[x$Quintile == 3] <- "#357BA2FF"
x$Colour[x$Quintile == 4] <- "#38AAACFF"
x$Colour[x$Quintile == 5] <- "#78D6AEFF"
x$Colour[x$Quintile == "Not compared"] <- "grey"

x$Colour <- factor(x$Colour, c("#342346FF", "#40498EFF", "#357BA2FF", "#38AAACFF",
                               "#78D6AEFF", "grey"))

area_comp <- plot_area_comparison_quint(data = x, value_type = value_type,
                                        show_ci = FALSE)

#### RBWM lsoas ###
i <- data$AreaCode %in% rbwm_lsoas
x <- data[i, ]

# Create quintiles for all LSOA data
quintiles <- quantile(x$Value, probs = seq(0, 1, by = 0.2), na.rm = TRUE) 
quintiles[1] <- round_any(quintiles[1], 0.1, f = floor)
quintiles[2:5] <- round_any(quintiles[2:5], 0.1, f = round)
quintiles[6] <- round_any(quintiles[6], 0.1, f = ceiling)

x$Quintile <- with(x, cut(Value, breaks = quintiles, include.lowest = TRUE, 
                          dig.lab = 5))

levels(x$Quintile) <- gsub("([0-9]+\\.[0-9]+)(\\])", "\\2\\1", levels(x$Quintile))
levels(x$Quintile) <- gsub("([0-9]+)(\\])", "\\2\\1", levels(x$Quintile))
levels(x$Quintile) <- gsub("\\(", ">", levels(x$Quintile))
levels(x$Quintile) <- gsub("\\]", "\u2264", levels(x$Quintile))
levels(x$Quintile) <- gsub("\\[", "\u2265", levels(x$Quintile))
levels(x$Quintile) <- gsub(",", " - ", levels(x$Quintile))

# The notation (a - b] means ">a and <=b".

levels(x$Quintile) <- c(levels(x$Quintile), "Not compared")
x$Quintile[is.na(x$Value)] <- "Not compared"

x$Quintile[x$AreaCode == eng_code] <- "Not compared"

x$Colour <- NA
x$Colour[x$Quintile == levels(x$Quintile)[1]] <- "#342346FF"
x$Colour[x$Quintile == levels(x$Quintile)[2]] <- "#40498EFF"
x$Colour[x$Quintile == levels(x$Quintile)[3]] <- "#357BA2FF"
x$Colour[x$Quintile == levels(x$Quintile)[4]] <- "#38AAACFF"
x$Colour[x$Quintile == levels(x$Quintile)[5]] <- "#78D6AEFF"
x$Colour[x$Quintile == "Not compared"] <- "grey"

x$Colour <- factor(x$Colour, c("#342346FF", "#40498EFF", "#357BA2FF", "#38AAACFF",
                               "#78D6AEFF", "grey"))


map <- map_quintile_indicator(data = x, shape_file = shp_lsoa, 
                              areas_to_map = rbwm_lsoas)

trend_plot <- paste0("No trend data available.")

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)
# add indicator to master dataset
#dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot, alt_text = trend_plot)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata)

```

```{r access_gardenspace, eval = incl_access_gardenspace}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
# ind_ID <- 
# ind_sex <- 
# ind_age <- 
title <- paste0("Access to garden space")
short_title <- paste0("Access to garden space")
additional_text <- NULL
notes <- NULL
#caveats <- NULL

value_type <- "Proportion (%)"
value_type_short <- "%"
# timeperiod <- "periods"
original_geography <- "MSOA"
#CI_level <- 0.95
confidence_interval_method <- paste0("Sample quantiles")
source <- paste0("Office for National Statistics. Access to gardens and public green space in Great Britain")

x <- read.csv(paste0("C:/Users/", Sys.getenv("username"), "/OneDrive - Royal Borough of Windsor and Maidenhead/PHI - Data and Analytics/Datasets/ONS/Access to gardens and public green space in Great Britain/MSOA-gardens.csv"))

colnames(x) <- gsub("^X.*", NA, colnames(x))


# Function to fill NA values with the preceding non-NA value
for (i in 2:ncol(x)) {
  if (is.na(colnames(x)[i])) {
    colnames(x)[i] <- colnames(x)[i - 1]
  }
}

colnames(x) <- paste0(colnames(x), x[1, ])

x <- x[-1, ]

x$`Property.type..TotalAddress count` <- as.numeric(x$`Property.type..TotalAddress count`)
x$`Property.type..TotalAdress with private outdoor space count` <- as.numeric(x$`Property.type..TotalAdress with private outdoor space count`)

LA <- aggregate(cbind(`Property.type..TotalAdress with private outdoor space count`,
                      `Property.type..TotalAddress count`) ~ 
                  LAD.code + LAD.name,
                data = x, FUN = sum)
colnames(LA) <- c("AreaCode", "AreaName", "Count", "Denominator")
LA$AreaType <- "Local authority"

i <- x$Country.code == eng_code
eng <- aggregate(cbind(`Property.type..TotalAdress with private outdoor space count`,
                      `Property.type..TotalAddress count`) ~ 
                   Country.code + Country.name,
                 data = x[i, ], FUN = sum)
colnames(eng) <- c("AreaCode", "AreaName", "Count", "Denominator")
eng$AreaType <- "England"

x <- x[, c("MSOA.code", "MSOA.name", 
           "Property.type..TotalAdress with private outdoor space count",
           "Property.type..TotalAddress count")]
colnames(x) <- c("AreaCode", "AreaName", "Count", "Denominator")
x$AreaType <- "MSOA"

x <- rbind(x, LA, eng)

x$Value <- x$Count / x$Denominator * 100
x$Timeperiod <- 2020

x$LowerCI95Limit <- PHEindicatormethods:::wilson_lower(x = x$Count, n = x$Denominator) * 100
x$LowerCI99.8Limit <- NA
x$UpperCI95Limit <- PHEindicatormethods:::wilson_upper(x = x$Count, n = x$Denominator) * 100
x$UpperCI99.8Limit <- NA

x <- create_comp_rag(data = x, low_is_good = FALSE)

data <- x
eng <- data[data$AreaCode == eng_code, ]
rbwm <- data[data$AreaCode == rbwm_code, ]

#### Local Authorities ####
x <- data[data$AreaType == "Local authority", ]

# Create quintiles for all LSOA data
quintiles <- quantile(x$Value, probs = seq(0, 1, by = 0.2), na.rm = TRUE) 
quintiles[1] <- round_any(quintiles[1], 0.1, f = floor)
quintiles[2:5] <- round_any(quintiles[2:5], 0.1, f = round)
quintiles[6] <- round_any(quintiles[6], 0.1, f = ceiling)

x <- rbind(x, eng)

x$Quintile <- with(x, cut(Value, breaks = quintiles, include.lowest = TRUE, 
                          labels = 1:5))
levels(x$Quintile) <- gsub(",", " - ", levels(x$Quintile))
# The notation (a - b] means ">a and <=b".

levels(x$Quintile) <- c(levels(x$Quintile), "Not compared")
x$Quintile[is.na(x$Value)] <- "Not compared"

x$Quintile[x$AreaCode == eng_code] <- "Not compared"

x$Colour <- NA
x$Colour[x$Quintile == 1] <- "#342346FF"
x$Colour[x$Quintile == 2] <- "#40498EFF"
x$Colour[x$Quintile == 3] <- "#357BA2FF"
x$Colour[x$Quintile == 4] <- "#38AAACFF"
x$Colour[x$Quintile == 5] <- "#78D6AEFF"
x$Colour[x$Quintile == "Not compared"] <- "grey"

x$Colour <- factor(x$Colour, c("#342346FF", "#40498EFF", "#357BA2FF", "#38AAACFF",
                               "#78D6AEFF", "grey"))



latest_value <- plot_latest_value_quint(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))

#### RBWM MSOAs ###
i <- data$AreaCode %in% rbwm_msoas
x <- data[i, ]

# Create quintiles for all LSOA data
quintiles <- quantile(x$Value, probs = seq(0, 1, by = 0.2), na.rm = TRUE) 
quintiles[1] <- round_any(quintiles[1], 0.1, f = floor)
quintiles[2:5] <- round_any(quintiles[2:5], 0.1, f = round)
quintiles[6] <- round_any(quintiles[6], 0.1, f = ceiling)

x <- rbind(x, rbwm, eng)

x$Quintile <- with(x, cut(Value, breaks = quintiles, include.lowest = TRUE, 
                          labels = 1:5))
levels(x$Quintile) <- gsub(",", " - ", levels(x$Quintile))
# The notation (a - b] means ">a and <=b".

levels(x$Quintile) <- c(levels(x$Quintile), "Not compared")
x$Quintile[is.na(x$Value)] <- "Not compared"

x$Quintile[x$AreaCode == eng_code] <- "Not compared"

x$Colour <- NA
x$Colour[x$Quintile == 1] <- "#342346FF"
x$Colour[x$Quintile == 2] <- "#40498EFF"
x$Colour[x$Quintile == 3] <- "#357BA2FF"
x$Colour[x$Quintile == 4] <- "#38AAACFF"
x$Colour[x$Quintile == 5] <- "#78D6AEFF"
x$Colour[x$Quintile == "Not compared"] <- "grey"

x$Colour <- factor(x$Colour, c("#342346FF", "#40498EFF", "#357BA2FF", "#38AAACFF",
                               "#78D6AEFF", "grey"))

i <- fingertips_msoa$AreaType == "MSOA"
msoa_names <- fingertips_msoa[i, c("AreaCode", "AreaName")]
msoa_names <- unique(msoa_names)
colnames(msoa_names) <- c("AreaCode", "MSOAName")

x <- merge(x = x, y = msoa_names, by = "AreaCode", all.x = TRUE)

x$AreaName[x$AreaType == "MSOA"] <- x$MSOAName[x$AreaType == "MSOA"]

area_comp <- plot_area_comparison_quint(data = x, value_type = value_type,
                                        show_ci = FALSE)

#### RBWM MSOAs ###
i <- data$AreaCode %in% rbwm_msoas
x <- data[i, ]

# Create quintiles for all LSOA data
quintiles <- quantile(x$Value, probs = seq(0, 1, by = 0.2), na.rm = TRUE) 
quintiles[1] <- round_any(quintiles[1], 0.1, f = floor)
quintiles[2:5] <- round_any(quintiles[2:5], 0.1, f = round)
quintiles[6] <- round_any(quintiles[6], 0.1, f = ceiling)

x <- rbind(x, rbwm, eng)

x$Quintile <- with(x, cut(Value, breaks = quintiles, include.lowest = TRUE, 
                          dig.lab = 5))

levels(x$Quintile) <- gsub("([0-9]+\\.[0-9]+)(\\])", "\\2\\1", levels(x$Quintile))
levels(x$Quintile) <- gsub("([0-9]+)(\\])", "\\2\\1", levels(x$Quintile))
levels(x$Quintile) <- gsub("\\(", ">", levels(x$Quintile))
levels(x$Quintile) <- gsub("\\]", "\u2264", levels(x$Quintile))
levels(x$Quintile) <- gsub("\\[", "\u2265", levels(x$Quintile))
levels(x$Quintile) <- gsub(",", " - ", levels(x$Quintile))

# The notation (a - b] means ">a and <=b".

levels(x$Quintile) <- c(levels(x$Quintile), "Not compared")
x$Quintile[is.na(x$Value)] <- "Not compared"

x$Quintile[x$AreaCode == eng_code] <- "Not compared"

x$Colour <- NA
x$Colour[x$Quintile == levels(x$Quintile)[1]] <- "#342346FF"
x$Colour[x$Quintile == levels(x$Quintile)[2]] <- "#40498EFF"
x$Colour[x$Quintile == levels(x$Quintile)[3]] <- "#357BA2FF"
x$Colour[x$Quintile == levels(x$Quintile)[4]] <- "#38AAACFF"
x$Colour[x$Quintile == levels(x$Quintile)[5]] <- "#78D6AEFF"
x$Colour[x$Quintile == "Not compared"] <- "grey"

x$Colour <- factor(x$Colour, c("#342346FF", "#40498EFF", "#357BA2FF", "#38AAACFF",
                               "#78D6AEFF", "grey"))

i <- fingertips_msoa$AreaType == "MSOA"
msoa_names <- fingertips_msoa[i, c("AreaCode", "AreaName")]
msoa_names <- unique(msoa_names)
colnames(msoa_names) <- c("AreaCode", "MSOAName")

x <- merge(x = x, y = msoa_names, by = "AreaCode", all.x = TRUE)

x$AreaName[x$AreaType == "MSOA"] <- x$MSOAName[x$AreaType == "MSOA"]

map <- map_quintile_indicator(data = x, shape_file = shp_msoa, 
                              areas_to_map = rbwm_msoas)

trend_plot <- paste0("No trend data available.")

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source)
metadata <- paste0("Definition: Addresses with a private outdoor space or shared garden.\n",
                   metadata)

# add indicator to master dataset
#dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot, alt_text = trend_plot)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r access_public_greenspace, eval = incl_access_public_greenspace}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
# ind_ID <- 
# ind_sex <- 
# ind_age <- 
title <- paste0("Access to public green space (within a five-minute walk)")
short_title <- paste0("Access to public green space")
additional_text <- NULL
notes <- NULL
caveats <- paste0("Public green space access indicator is restricted to built up areas postcodes only")

value_type <- "Proportion (%)"
value_type_short <- "%"
# timeperiod <- "periods"
original_geography <- "Postcode"
#CI_level <- 0.95
confidence_interval_method <- paste0("Sample quantiles")
source <- paste0("Office for National Statistics. Access to gardens and public green space in Great Britain")

x <- read.csv(paste0("C:/Users/", Sys.getenv("username"), "/OneDrive - Royal Borough of Windsor and Maidenhead/PHI - Data and Analytics/Datasets/ONS/Access to gardens and public green space in Great Britain/LSOA-Parks-and-Playing-Fields.csv"))

x <- merge(x = x, y = lsoa_ward_lad, by.x = "LSOA.code", by.y = "LSOA21CD", 
           all.x = TRUE)

ward <- aggregate(cbind(Number.of.built.up.area.postcodes..within.300m.of.a.Park..Public.Garden..or.Playing.Field,
                        Number.of.postcodes.within.built.up.area) ~ 
                    WD24CD + WD24NM,
                  data = x, FUN = sum)
colnames(ward) <- c("AreaCode", "AreaName", "Count", "Denominator")
ward$AreaType <- "Ward"


LA <- aggregate(cbind(Number.of.built.up.area.postcodes..within.300m.of.a.Park..Public.Garden..or.Playing.Field,
                      Number.of.postcodes.within.built.up.area) ~ 
                  LAD.code + LAD.name,
                data = x, FUN = sum)
colnames(LA) <- c("AreaCode", "AreaName", "Count", "Denominator")
LA$AreaType <- "Local authority"

i <- x$Country.code == eng_code
eng <- aggregate(cbind(Number.of.built.up.area.postcodes..within.300m.of.a.Park..Public.Garden..or.Playing.Field,
                       Number.of.postcodes.within.built.up.area) ~ 
                   Country.code + Country.name,
                 data = x[i, ], FUN = sum)
colnames(eng) <- c("AreaCode", "AreaName", "Count", "Denominator")
eng$AreaType <- "England"

x <- x[, c("LSOA.code", "LSOA.name", 
           "Number.of.built.up.area.postcodes..within.300m.of.a.Park..Public.Garden..or.Playing.Field",
           "Number.of.postcodes.within.built.up.area")]
colnames(x) <- c("AreaCode", "AreaName", "Count", "Denominator")
x$AreaType <- "LSOA"

x <- rbind(x, ward, LA, eng)

x$Value <- x$Count / x$Denominator * 100
x$Timeperiod <- 2020

x$LowerCI95Limit <- PHEindicatormethods:::wilson_lower(x = x$Count, n = x$Denominator) * 100
x$LowerCI99.8Limit <- NA
x$UpperCI95Limit <- PHEindicatormethods:::wilson_upper(x = x$Count, n = x$Denominator) * 100
x$UpperCI99.8Limit <- NA

x <- create_comp_rag(data = x, low_is_good = FALSE)

data <- x
eng <- data[data$AreaCode == eng_code, ]
rbwm <- data[data$AreaCode == rbwm_code, ]

#### Local Authorities ####
x <- data[data$AreaType == "Local authority", ]

# Create quintiles for all LSOA data
quintiles <- quantile(x$Value, probs = seq(0, 1, by = 0.2), na.rm = TRUE) 
quintiles[1] <- round_any(quintiles[1], 0.1, f = floor)
quintiles[2:5] <- round_any(quintiles[2:5], 0.1, f = round)
quintiles[6] <- round_any(quintiles[6], 0.1, f = ceiling)

x <- rbind(x, eng)

x$Quintile <- with(x, cut(Value, breaks = quintiles, include.lowest = TRUE, 
                          labels = 1:5))
levels(x$Quintile) <- gsub(",", " - ", levels(x$Quintile))
# The notation (a - b] means ">a and <=b".

levels(x$Quintile) <- c(levels(x$Quintile), "Not compared")
x$Quintile[is.na(x$Value)] <- "Not compared"

x$Quintile[x$AreaCode == eng_code] <- "Not compared"

x$Colour <- NA
x$Colour[x$Quintile == 1] <- "#342346FF"
x$Colour[x$Quintile == 2] <- "#40498EFF"
x$Colour[x$Quintile == 3] <- "#357BA2FF"
x$Colour[x$Quintile == 4] <- "#38AAACFF"
x$Colour[x$Quintile == 5] <- "#78D6AEFF"
x$Colour[x$Quintile == "Not compared"] <- "grey"

x$Colour <- factor(x$Colour, c("#342346FF", "#40498EFF", "#357BA2FF", "#38AAACFF",
                               "#78D6AEFF", "grey"))

latest_value <- plot_latest_value_quint(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))

#### RBWM wards ###
i <- data$AreaCode %in% rbwm_wards
x <- data[i, ]

# Create quintiles for all LSOA data
quintiles <- quantile(x$Value, probs = seq(0, 1, by = 0.2), na.rm = TRUE) 
quintiles[1] <- round_any(quintiles[1], 0.1, f = floor)
quintiles[2:5] <- round_any(quintiles[2:5], 0.1, f = round)
quintiles[6] <- round_any(quintiles[6], 0.1, f = ceiling)

x <- rbind(x, rbwm, eng)

x$Quintile <- with(x, cut(Value, breaks = quintiles, include.lowest = TRUE, 
                          labels = 1:5))
levels(x$Quintile) <- gsub(",", " - ", levels(x$Quintile))
# The notation (a - b] means ">a and <=b".

levels(x$Quintile) <- c(levels(x$Quintile), "Not compared")
x$Quintile[is.na(x$Value)] <- "Not compared"

x$Quintile[x$AreaCode == eng_code] <- "Not compared"

x$Colour <- NA
x$Colour[x$Quintile == 1] <- "#342346FF"
x$Colour[x$Quintile == 2] <- "#40498EFF"
x$Colour[x$Quintile == 3] <- "#357BA2FF"
x$Colour[x$Quintile == 4] <- "#38AAACFF"
x$Colour[x$Quintile == 5] <- "#78D6AEFF"
x$Colour[x$Quintile == "Not compared"] <- "grey"

x$Colour <- factor(x$Colour, c("#342346FF", "#40498EFF", "#357BA2FF", "#38AAACFF",
                               "#78D6AEFF", "grey"))

area_comp <- plot_area_comparison_quint(data = x, value_type = value_type,
                                        show_ci = FALSE)

#### RBWM lsoas ###
i <- data$AreaCode %in% rbwm_lsoas
x <- data[i, ]

# Create quintiles for all LSOA data
quintiles <- quantile(x$Value, probs = seq(0, 1, by = 0.2), na.rm = TRUE) 
quintiles[1] <- round_any(quintiles[1], 0.1, f = floor)
quintiles[2:5] <- round_any(quintiles[2:5], 0.1, f = round)
quintiles[6] <- round_any(quintiles[6], 0.1, f = ceiling)

x$Quintile <- with(x, cut(Value, breaks = quintiles, include.lowest = TRUE, 
                          dig.lab = 5))

levels(x$Quintile) <- gsub("([0-9]+\\.[0-9]+)(\\])", "\\2\\1", levels(x$Quintile))
levels(x$Quintile) <- gsub("([0-9]+)(\\])", "\\2\\1", levels(x$Quintile))
levels(x$Quintile) <- gsub("\\(", ">", levels(x$Quintile))
levels(x$Quintile) <- gsub("\\]", "\u2264", levels(x$Quintile))
levels(x$Quintile) <- gsub("\\[", "\u2265", levels(x$Quintile))
levels(x$Quintile) <- gsub(",", " - ", levels(x$Quintile))

# The notation (a - b] means ">a and <=b".

levels(x$Quintile) <- c(levels(x$Quintile), "Not compared")
x$Quintile[is.na(x$Value)] <- "Not compared"

x$Quintile[x$AreaCode == eng_code] <- "Not compared"

x$Colour <- NA
x$Colour[x$Quintile == levels(x$Quintile)[1]] <- "#342346FF"
x$Colour[x$Quintile == levels(x$Quintile)[2]] <- "#40498EFF"
x$Colour[x$Quintile == levels(x$Quintile)[3]] <- "#357BA2FF"
x$Colour[x$Quintile == levels(x$Quintile)[4]] <- "#38AAACFF"
x$Colour[x$Quintile == levels(x$Quintile)[5]] <- "#78D6AEFF"
x$Colour[x$Quintile == "Not compared"] <- "grey"

x$Colour <- factor(x$Colour, c("#342346FF", "#40498EFF", "#357BA2FF", "#38AAACFF",
                               "#78D6AEFF", "grey"))


map <- map_quintile_indicator(data = x, shape_file = shp_lsoa, 
                              areas_to_map = rbwm_lsoas)

trend_plot <- paste0("No trend data available.")

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source,
                          caveats = caveats)

# add indicator to master dataset
#dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot, alt_text = trend_plot)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

```{r access_secondary_school, eval = incl_access_secondary_school}

slide_num <- slide_num + 1
theme <- NULL

# Metadata
# ind_ID <- 
# ind_sex <- 
# ind_age <- 
title <- paste0("Access to secondary school within 30 minutes by public transport or walking")
short_title <- "Access to secondary school"
additional_text <- NULL
notes <- NULL
caveats <- paste0("Public green space access indicator is restricted to built up areas postcodes only")

value_type <- "Proportion (%)"
value_type_short <- "%"
# timeperiod <- "periods"
original_geography <- "Postcode"
CI_level <- 0.95
confidence_interval_method <- paste0("Wilson Score CI method (", CI_level * 100,"%)")
source <- "Department for Transport. Journey time statistics"
notes <- "Definition: Service users able to access a secondary school within 30-minutes by public transport or walking.\n"

x <- readRDS(paste0("C:/Users/", Sys.getenv("username"), "/OneDrive - Royal Borough of Windsor and Maidenhead/PHI - Data and Analytics/Datasets/gov.uk/Journey time statistics data tables (JTS)/lower super output area (JTS05)/JTS0503/processed-data/secondary-school-30min-travel.Rds"))

ward <- merge(x = x, y = lsoa_ward_lad, by.x = "AreaCode", by.y = "LSOA21CD", 
              all.x = TRUE)

ward <- aggregate(cbind(Count, Denominator) ~ WD24CD + WD24NM, data = ward,
                  FUN = sum)
colnames(ward) <- c("AreaCode", "AreaName", "Count", "Denominator")
ward$AreaType <- "Ward"

ward$Value <- ward$Count / ward$Denominator * 100

x <- rbind(x, ward)

x$Timeperiod <- 2019

x$Count <- round(x$Count)

x$LowerCI95Limit <- PHEindicatormethods:::wilson_lower(x = x$Count, n = x$Denominator) * 100
x$LowerCI99.8Limit <- NA
x$UpperCI95Limit <- PHEindicatormethods:::wilson_upper(x = x$Count, n = x$Denominator) * 100
x$UpperCI99.8Limit <- NA

x <- create_comp_rag(data = x, low_is_good = FALSE)

latest_value <- plot_latest_value(data = x, value_type = value_type)
latest_period <- paste0("Latest time period: ", max(x$Timeperiod))

i <- x$AreaCode %in% c(eng_code, rbwm_code, rbwm_wards)
area_comp <- plot_area_comparison(data = x[i, ], value_type = value_type,
                                  show_legend = FALSE)
map <- map_rag_indicator(data = x, shape_file = shp_lsoa,
                         areas_to_map = rbwm_lsoas)

trend_plot <- paste0("No trend data available.")

metadata <- text_metadata(value_type = value_type, 
                          original_geography = original_geography, 
                          ci_method = confidence_interval_method,
                          source = source,
                          caveats = caveats)

# add indicator to master dataset
#dataset <- rbind(dataset, x)

# Add slide
mydoc <- add_slide(mydoc, layout = "jlhws", master = "PHI profiles")
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "title"),
                 value = title)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "slide number"), 
                 value = slide_num)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "version"), 
                 value = paste0("Version ", format(version_num, nsmall = 1)))
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "overview"), 
                 value = latest_value$plot, alt_text = latest_value$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "latest period"), 
                 value = latest_period, alt_text = latest_period)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "trend"), 
                 value = trend_plot, alt_text = trend_plot)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "compare areas"), 
                 value = area_comp$plot, alt_text = area_comp$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "map"), 
                 value = map$plot, alt_text = map$alt_text)
mydoc <- ph_with(mydoc, location = ph_location_label(ph_label = "metadata"), 
                 value = metadata) 

```

``` {r finish.code}

outfile <- paste0("../output/RBWM-JHWBS-profile-", format(version_num, nsmall = 1), ".pptx")
print(mydoc, target = outfile)

# Save dataset
if(save_dataset == TRUE){
  saveRDS(dataset, paste0("C:/Users/", Sys.getenv("username"), "/OneDrive - Royal Borough of Windsor and Maidenhead/PHI - Data and Analytics/Datasets/Profiles/JHWBS profile/RBWM-JWHBS-data-", format(version_num, nsmall = 1),".Rds"))
}

t2 <- Sys.time()
duration <- difftime(t2, t1, units = "secs")
# status.log(paste("This took", duration, "seconds"))

```
